### ISSUE TITLE
signal display gui error

### ISSUE THREAD

**Issue by judos** [Zomis/FactorioMods#18]
Hi there,
In a multiplayer game where I tried the "visual signals" mod of yours I got this error when placing the first signal display:
"Error while running event visual-signals::on_tick (ID 0)
__visual-signals__/control.lua:166: attempt to index field 'gui_signal_display' (a nil value)"

I'm player number 2 on that map so maybe it's multiplayer related?
Thanks for checking!

**Comment by Zomis** [comment]
Hmm. Interesting. I must admit that I have never tried this in a multiplayer game (shame on me!). Is it reproducible? Have you gotten the mod to work in a multiplayer game at any time?

I will open up the code and start investigating.

**Comment by Zomis** [comment]
I see the problem, expect a fix tomorrow!

**Comment by judos** [comment]
Cool thanks! I have never used it before in multiplayer.
Multiplayer is where the use case also becomes interesting. Maybe players would like to display something for themselves or something for everyone. A lot of possible extensions I see here. But for me right now it would be fine if the display just shows the same for everyone :)

**Comment by Zomis** [comment]
Updated now. Please let me know if you continue to experience problems!

When placed, it will show for everyone in the force but each player has the possibility to show/hide individual circuit network displays by using the icon at the top.
