### ISSUE TITLE
0.15.22 update broke Visual Signal mod.

### ISSUE THREAD

**Issue by minyan** [Zomis/FactorioMods#20]
Upon load, it no longer can detect signal. Must be deconstructed and placed again.

**Comment by Zomis** [comment]
Unable to reproduce.
What do you mean by "detect signal"? Are the GUI items removed or are they not visible but not updating?

Are you sure that you didn't temporarily disabled the mod, and then enabled it again?

**Comment by minyan** [comment]
GUI were removed..  
I'm sure i didn't temporarily disabled mod, if so, how come i can build one after load?  
Happen In 0.15.22, 
Edit : 
Resolved in 0.15.23
Turns out it was a bug on dev part.
https://forums.factorio.com/viewtopic.php?t=50055

**Comment by Zomis** [comment]
Thanks. I had a feeling it could be a Factorio bug.
