### ISSUE TITLE
Categories?

### ISSUE THREAD

**Issue by abordoli** [Zomis/FactorioMods#21]
What does one press to itemize items into categories like in the first picture shown at the mod portal?
Regards,
~B

**Comment by Zomis** [comment]
You press the visual signals icon in the top of your GUI. It's not really *categories*, it's different GUI Signal Displays.

- Research "Visual Signals"
- Build a "GUI Signal Display" and place it on the map
- Connect the GUI Signal Display to a circuit network that has some signals
- Click the icon at the top to change names of your GUI Signal Displays

**Comment by abordoli** [comment]
Simon,Thanks! I didn't notice the button.

I think I have an idea as to how to make categories (different groupings).Regards,Antony

**Comment by Zomis** [comment]
Okay, and what is your idea about how to make different categories?

**Comment by abordoli** [comment]
You're right. Categories isn't really what's happening. Just rows of different networks signals logically lumped together.
What I am wondering, though, is....IS there a way to move rows up and down?...Like a priority type system. Right now, I'm just being really careful to set things up from raw-->more-finished, but a feature to rearrange the networks would be awesome!
Thanks for the great mod,Antony

**Comment by abordoli** [comment]
Do you use Discord? I do have some examples and ideas if you'd like to see/chat about them.

**Comment by abordoli** [comment]
I find a way to alter the order of signal groups by everything and showing them one-by-one in the desired order.

Personally, my only challenge now is to find a way to get count readings on all of the dispersed mines. I do have the counts on my red-wire network, but it contains stuff that I've already grouped out. The main object being to thin down the width of the gui to say 5 items wide per grouping. OFC, this then runs them down off the page which means I'll nee d to prioritize which ones to "show"

**Comment by Zomis** [comment]
I have created a Github issue, #22, for an easy way to reorder Visual Signals.

Please use Github for suggesting new ideas.

**Comment by abordoli** [comment]
Roger!

**Comment by Zomis** [comment]
It seems like I have addressed all things here so I will close this issue. Feel free to add a comment if you have further questions.

**Comment by abordoli** [comment]
I've been playing recently and have noticed that the "show" box is still on the very right and prioritizing/ordering within the gui is not yet possible.

Still plans for these tweaks?

**Comment by Zomis** [comment]
Yes, I still plan on fixing this. I have just been occupied with other things. For example, I have released two new mods. If you haven't seen them, check https://mods.factorio.com/mods/zomis/

**Comment by abordoli** [comment]
I'll give the "What is Missing" a try. The "Lamp Placer" I saw, but am quite confused despite the graphics and description. Does it recommend via a blue-print, where lamps should be placed?

**Comment by Zomis** [comment]
It's a selection tool that when used, an algorithm will place lamp-ghosts where there is electricity and no other lamps nearby.

**Comment by abordoli** [comment]
Ah, I see...
