### ISSUE TITLE
Visual Signals: New Bug When Removing and Putting Down Another VS Combinator

### ISSUE THREAD

**Issue by abordoli** [Zomis/FactorioMods#27]
Topic...

**Comment by Zomis** [comment]
From what you wrote on Discord:

    Error while running event visual signals:on_built_entity
    Gui element with name label17 already present in the parent element.
    stack traceback:
    []__visual signals__/control.lua:47 in function 'createGUI'
    []__visual signals__/control.lua:136 in function <__visual signals__/control.lua:124>

**Comment by abordoli** [comment]
Yeah...so specifically, you can't pick up any previously placed GUI combinatory and place another one down atm. Seems like the one's being picked up are not removing themselves properly since one of the new mod updates.

**Comment by Zomis** [comment]
Whoops. I did not know that it could be reproduced so easily. Alright, I have found the issue and will fix it.
