### ISSUE TITLE
If you have no visual signals placed and you click the menu icon (in the upper left) it crashes to the title screen

### ISSUE THREAD

**Issue by zachary-D** [Zomis/FactorioMods#31]
I didn't get a good look at the error message, but it said it was an index error.  I assume it tried to index the visual signals, but because there were none, it tried to index null.  Based off my (fairly poor) knowledge of LUA, you should probably be able to fix this easily by adding a check to see if items exist before trying to index them.

(I'd label this with the bug tag, but I can't find the button, do I not have perms or am I blind?)

**Comment by Zomis** [comment]
Only the owner of a repository can label issues. Thanks for the report, I will fix this in the next update (which is unfortunately not scheduled)

**Comment by zachary-D** [comment]
If I fix it and make a PR for it, would that help?  (Assuming I figure out how to fix it)

**Comment by Zomis** [comment]
Pull Requests are always welcome.

A simple workaround seems to be to not click the button when you have no Visual Signals though :D

**Comment by zachary-D** [comment]
That doesn't account for me clicking it instead of the button for my to-do list :P

(Or me going "I wonder if I still have one set up......")

**Comment by Zomis** [comment]
I am updating the mod for 0.16 and this will be fixed in that update. Expected to be released today or tomorrow.

**Comment by Zomis** [comment]
Fixed in version 0.16.1. Thanks for your feedback.

**Comment by zachary-D** [comment]
Cool!
