### ISSUE TITLE
Advanced Combinator: Crashed, can't close window

### ISSUE THREAD

**Issue by digzol** [Zomis/FactorioMods#39]
Map crashed with the command window opened (tried entering ' * ' instead of a number value then applying). Next time I load from autosave, the command window pops up, but pressing Close does nothing.

**Comment by Zomis** [comment]
Do you have any more details regarding the error that you got? Any specific error message?

If possible I would also like screenshots on how it looked before it crashed, when it crashed, and when you load from autosave.

**Comment by digzol** [comment]
(late reply much, sorry)

1. The crash error was a type of "nil value found" I believe. It was for a count field for signal (i.e. tried entering the value "'*'x iron" instead of "3x iron". Sorry, can't really give more details than this.

2. If the game autosaved while the combinator window was opened and the client crashed (possibly other causes too?) next time the map loads, the window will still be open but the "close" window button won't be working. Might be it's own bug.

**Comment by Zomis** [comment]
Another report with some more details on this: https://mods.factorio.com/mod/advanced-combinator/discussion/5f1d01c2feb4ea560314ea96

Hopefully it should be reproducible and fixable.

**Comment by Zomis** [comment]
From the default code, change the "1" in the second line to something like "dsa*1".

This leads to it not being able to parse it as a number.

signal_set.lua:9: attempt to compare nil with number
stack traceback:
signal_set.lua:9 in function 'set_signal'
signal_set.lua:45 in function signal_set.lua:42

model.lua:74 in function 'func'
model.lua:17 in function 'perform'
control.lua:85 in function <control.lua:79>

**Comment by Zomis** [comment]
Version 0.18.1 has now been uploaded where this has hopefully been fixed.
