### ISSUE TITLE
Odd behavior on Advanced Combinator

### ISSUE THREAD

**Issue by adalast** [Zomis/FactorioMods#42]
So I'm trying to use the Advanced Combinator to automate sat production in conjunction with the Crafting Combinator, but it is giving me some issues.  Specifically, I am currently trying to get the an automation for Solar Panels 3s.  I have the reads coming in from my storage to determine the cases on what is present, but after that is where it falls apart.  I have tried a bitwise-and and an addition to see if I can get the triggers to fire right, but I cannot.  I have tracked it down to not understanding what the const field is for at the end of the value_of_signal function.  I am assuming that is to read the value on the combinator rather than the incoming line.  Maybe that is my issue.  I want to do my comparisons and get my boolean values, then use those to determine what to craft.  What am I not getting?

if(compare(green(this,item/solar-panel),>,const(0)),set_signal(const(7),signal(signal_type(virtual/signal-0),const(1))));
if(compare(green(this,item/solar-panel-2),>,const(0)),set_signal(const(8),signal(signal_type(virtual/signal-1),const(1))));
if(compare(green(this,item/solar-panel-3),<,const(300)),set_signal(const(9),signal(signal_type(virtual/signal-2),const(1))));
if(compare(add(value_of_signal(signal(signal_type(virtual/signal-0),const(1))),value_of_signal(signal(signal_type(virtual/signal-0),const(1)))),=,const(2)),set_signal(const(1),signal(signal_type(virtual/signal-A),const(1))));

**Comment by Zomis** [comment]
What is the problem you are experiencing in the game?

Do you have a savegame that I could check?

**Comment by adalast** [comment]
I could submit my savegame, yeah.  Honestly, I am getting incorrect outputs from the function.  When I do the bitwise-and with constants, it processes correctly, the instant I switch to value_of_signal() it starts messing up and giving me incorrect results.

**Comment by adalast** [comment]
The savegame is 140 hours of spaghetti though.

**Comment by Zomis** [comment]
Ok, so if you do this part: `value_of_signal(signal(signal_type(virtual/signal-0),const(1))`
You will create a signal of type virtual/signal-0 with the constant value 1.
Then you will take the value of that signal, which will be 1.
So that part can essentially be replaced with `const(1)`.

Does this make it clearer what's going on?

**Comment by adalast** [comment]
Not exactly, how do I get the value of a signal that is being generated by the combinator?

**Comment by Zomis** [comment]
Due to lack of response, I assume that all questions were clarified and the problem solved. Get back to me if that's not the case.
