### ISSUE TITLE
Crash on 0.18.30 when checking what is missing for current tech

### ISSUE THREAD

**Issue by Panderine** [Zomis/FactorioMods#43]
This is the trace:

  https://pastebin.com/raw/E0G7gJDN

**Comment by Zomis** [comment]
Hi and thanks for a good bug report. Problem has been identified and will be fixed shortly.

It seems like you have built a lab and then later de-constructed it but the mod has not registered the deconstruction. May I ask how you de-constructed it, if you know?

**Comment by Panderine** [comment]
mmm I don't remember doing that. Although I did put down some advanced lab to compare with the normal lab from Krastorio 2 which i'm playing now. Don't now if this was the issue but I had several version changes in the mean time I'm sure. I detected the issue with  version .30 but I'm not sure if it was happening before. Also removing was done by hand and/or by construction bots mod.  Maybe some issue there or with other mod/crash? I had several crashes with other mods as well that could have affected something.

Also I have some lab's ghosts still. I could try removing them and checking if the crash still occurs.

**Comment by Zomis** [comment]
> Also removing was done by hand and/or by construction bots mod. Maybe some issue there or with other mod/crash?

Ah, thanks. This explains it. I think it is misbehaving when being destructed by construction bots mod. I will try to find time to fix this soon.

**Comment by Zomis** [comment]
I have just uploaded What is Missing 0.18.2 that contains several changes, please try it out and let me know if this bug still exists, or if any other bugs have been created in its place.
