### ISSUE TITLE
Crash on boot (v1.0.0)

### ISSUE THREAD

**Issue by Mernom** [Zomis/FactorioMods#50]
135.596 Error MainLoop.cpp:1207: Exception at tick 0: The mod Advanced Combinator (0.18.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event advanced-combinator::on_tick (ID 0)
__advanced-combinator__/control.lua:86: bad argument #1 of 2 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	__advanced-combinator__/control.lua:86: in function <__advanced-combinator__/control.lua:85>

**Comment by Zomis** [comment]
Is this in Factorio 1.0.0 ? Did it work to load in 0.18.47 or when was the last time you played this?

**Comment by Mernom** [comment]
indeed v1. Happened as a soon as I started a new map. Could be due to the starting cutscene?

**Comment by Zomis** [comment]
Nope, it's because of a stupid programmer who didn't test starting a new map after last time he made an update to the mod 🤦‍♂️

**Comment by Zomis** [comment]
Thank you for this bug report. 0.18.2 has now been uploaded (it is also compatible with 1.0.0). Thank you for using this mod and enjoy!
