### ISSUE TITLE
Mod is responsible for long load times when using a lot of trains.

### ISSUE THREAD

**Issue by TunikaGruss** [Zomis/FactorioMods#52]
I have a huge Train based base and am using this mod. When using this mod for 100+ hours my savegame will take up to 20-30x longer than usual. This is caused by the savegame file, specifically the script.dat file being 300mb with the mod, and 3,5mb without the mod. I dont think that you intentionally did this, but maybe put a disclaimer on the mod page so that people using this mod are not surprised by long load and save times.
If you want, I can send you my save files with and without the mod activated.

**Comment by Zomis** [comment]
I am aware of the problem, I have considered the possibility that this might happen.

I think that if you open the mod and click the trash button to remove older events, it will go a lot faster again.

Any suggestion for how I could fix the problem permanently are welcome.

**Comment by Zomis** [comment]
I have been aware for quite some time that this was an issue, and I have also heard from others who haven't cleared their logs in a long while.

I am not playing Factorio much these days so motivation to fix this has been very low, but today I finally fixed this issue.

As of version 1.1.5, Train Log will now automatically clear train logs older than 24 hours.
