### ISSUE TITLE
Crash on Click on "Clear all older entries"

### ISSUE THREAD

**Issue by Vystella** [Zomis/FactorioMods#59]
Hi,  when i click on "Clear all older entries" in the GUI i got the following error and the Game crashes.
Is that known?

Error while running event train-log::on_gui_click (ID 1)
__train-log__/gui/toolbar.lua:19: attempt to index field 'filter' (a nil value)
stack traceback:
	__train-log__/gui/toolbar.lua:19: in function 'handler'
	__train-log__/gui/main_gui.lua:125: in function 'wrapper'
	__flib__/gui.lua:147: in function 'handler'
	__flib__/gui.lua:177: in function <__flib__/gui.lua:160>

**Comment by Zomis** [comment]
Whoops, fixed now! Thanks.
